name: Test API endpoints
on: [push]
jobs:
  runtests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        # health checks
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        working-directory: ./budgetee-server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        working-directory: ./budgetee-server
        run: python -m pytest -s --import-mode=append tests/
        env:
          APP_SECRET: f06709g6df9s87gd0f98g6s0d9
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres