name: Test API endpoints
on: [push]
jobs:
  runtests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies and run tests
        working-directory: ./budgetee-server
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pytest
        env:
          APP_SECRET: f06709g6df9s87gd0f98g6s0d9
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres